USE tech_summit;

INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (4, 'berta', 'navarro', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (5, 'nil', 'soler', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (6, 'oriol', 'serra', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (7, 'marc', 'roca', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (8, 'marc', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (9, 'joan', 'vidal', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (10, 'oriol', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (11, 'marta', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (12, 'laia', 'sanz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (13, 'carla', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (14, 'clara', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (15, 'jordi', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (16, 'oriol', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (17, 'oriol', 'soler', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (18, 'clara', 'roca', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (19, 'nora', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (20, 'berta', 'duran', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (21, 'anna', 'navarro', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (22, 'oriol', 'rovira', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (23, 'clara', 'ortega', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (24, 'clara', 'rovira', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (25, 'marc', 'garcia', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (26, 'joan', 'costa', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (27, 'clara', 'casas', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (28, 'adria', 'molina', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (29, 'anna', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (30, 'pol', 'iglesias', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (31, 'david', 'ortega', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (32, 'clara', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (33, 'anna', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (34, 'oriol', 'ruiz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (35, 'xavi', 'serra', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (36, 'marc', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (37, 'anna', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (38, 'irene', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (39, 'oriol', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (40, 'xavi', 'ruiz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (41, 'marc', 'duran', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (42, 'adria', 'serra', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (43, 'pau', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (44, 'clara', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (45, 'david', 'casas', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (46, 'carla', 'campos', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (47, 'oriol', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (48, 'laia', 'molina', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (49, 'berta', 'casas', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (50, 'oriol', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (51, 'jordi', 'campos', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (52, 'pol', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (53, 'jordi', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (54, 'oriol', 'casas', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (55, 'laia', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (56, 'nora', 'campos', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (57, 'aina', 'garcia', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (58, 'joan', 'soler', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (59, 'joan', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (60, 'joan', 'font', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (61, 'pol', 'casas', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (62, 'aina', 'serra', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (63, 'clara', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (64, 'laia', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (65, 'pol', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (66, 'anna', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (67, 'pau', 'serra', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (68, 'nil', 'serra', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (69, 'marta', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (70, 'xavi', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (71, 'nil', 'garcia', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (72, 'clara', 'font', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (73, 'nil', 'ruiz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (74, 'aina', 'duran', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (75, 'david', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (76, 'marc', 'marti', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (77, 'berta', 'garcia', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (78, 'jordi', 'casas', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (79, 'david', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (80, 'marta', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (81, 'jordi', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (82, 'marta', 'navarro', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (83, 'clara', 'molina', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (84, 'eric', 'vidal', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (85, 'carla', 'navarro', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (86, 'nora', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (87, 'laia', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (88, 'anna', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (89, 'anna', 'soler', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (90, 'jordi', 'campos', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (91, 'marta', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (92, 'anna', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (93, 'carla', 'sanz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (94, 'marta', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (95, 'xavi', 'marti', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (96, 'xavi', 'rovira', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (97, 'anna', 'molina', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (98, 'david', 'pujol', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (99, 'joan', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (100, 'aina', 'iglesias', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (101, 'clara', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (102, 'pau', 'sanz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (103, 'clara', 'duran', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (104, 'clara', 'pujol', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (105, 'xavi', 'iglesias', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (106, 'eric', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (107, 'marta', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (108, 'jordi', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (109, 'marta', 'molina', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (110, 'xavi', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (111, 'clara', 'casas', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (112, 'xavi', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (113, 'clara', 'duran', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (114, 'nora', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (115, 'jordi', 'pujol', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (116, 'joan', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (117, 'david', 'serra', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (118, 'oriol', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (119, 'anna', 'casas', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (120, 'anna', 'pujol', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (121, 'jordi', 'rovira', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (122, 'aina', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (123, 'nil', 'ferrer', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (124, 'nil', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (125, 'carla', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (126, 'eric', 'pujol', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (127, 'marta', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (128, 'carla', 'navarro', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (129, 'jordi', 'serra', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (130, 'marc', 'rovira', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (131, 'david', 'garcia', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (132, 'joan', 'soler', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (133, 'clara', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (134, 'eric', 'molina', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (135, 'clara', 'ferrer', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (136, 'nil', 'sanz', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (137, 'pol', 'pujol', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (138, 'oriol', 'vidal', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (139, 'david', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (140, 'xavi', 'sanz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (141, 'nora', 'ortega', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (142, 'david', 'vidal', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (143, 'berta', 'casas', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (144, 'jordi', 'sanz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (145, 'david', 'marti', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (146, 'laia', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (147, 'adria', 'campos', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (148, 'laia', 'duran', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (149, 'nil', 'pujol', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (150, 'anna', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (151, 'joan', 'iglesias', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (152, 'carla', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (153, 'david', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (154, 'pol', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (155, 'pau', 'rovira', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (156, 'david', 'vidal', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (157, 'nora', 'roca', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (158, 'pol', 'serra', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (159, 'jordi', 'casas', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (160, 'nil', 'ortega', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (161, 'nil', 'campos', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (162, 'nora', 'pujol', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (163, 'david', 'roca', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (164, 'berta', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (165, 'berta', 'molina', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (166, 'marta', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (167, 'marc', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (168, 'aina', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (169, 'marc', 'campos', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (170, 'carla', 'iglesias', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (171, 'anna', 'molina', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (172, 'xavi', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (173, 'jordi', 'molina', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (174, 'berta', 'pujol', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (175, 'aina', 'ruiz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (176, 'marta', 'molina', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (177, 'clara', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (178, 'berta', 'campos', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (179, 'irene', 'ruiz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (180, 'aina', 'molina', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (181, 'pol', 'vidal', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (182, 'eric', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (183, 'marc', 'font', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (184, 'irene', 'vidal', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (185, 'nil', 'costa', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (186, 'laia', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (187, 'eric', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (188, 'eric', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (189, 'jordi', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (190, 'irene', 'font', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (191, 'marc', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (192, 'joan', 'roca', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (193, 'irene', 'sanz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (194, 'pau', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (195, 'oriol', 'garcia', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (196, 'irene', 'ferrer', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (197, 'nil', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (198, 'eric', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (199, 'eric', 'sanz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (200, 'oriol', 'sanz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (201, 'pau', 'duran', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (202, 'joan', 'serra', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (203, 'nil', 'campos', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (204, 'berta', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (205, 'berta', 'duran', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (206, 'irene', 'serra', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (207, 'berta', 'marti', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (208, 'david', 'garcia', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (209, 'nora', 'vidal', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (210, 'marc', 'pujol', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (211, 'nora', 'costa', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (212, 'laia', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (213, 'berta', 'casas', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (214, 'irene', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (215, 'pol', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (216, 'jordi', 'garcia', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (217, 'irene', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (218, 'marc', 'navarro', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (219, 'nil', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (220, 'nora', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (221, 'xavi', 'iglesias', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (222, 'david', 'garcia', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (223, 'marta', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (224, 'eric', 'roca', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (225, 'nil', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (226, 'carla', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (227, 'irene', 'pujol', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (228, 'david', 'costa', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (229, 'carla', 'ruiz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (230, 'jordi', 'costa', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (231, 'xavi', 'molina', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (232, 'aina', 'garcia', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (233, 'anna', 'garcia', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (234, 'nora', 'duran', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (235, 'pol', 'sanz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (236, 'marta', 'ortega', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (237, 'eric', 'ortega', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (238, 'nora', 'font', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (239, 'aina', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (240, 'pol', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (241, 'xavi', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (242, 'berta', 'duran', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (243, 'berta', 'pujol', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (244, 'irene', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (245, 'aina', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (246, 'berta', 'campos', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (247, 'xavi', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (248, 'irene', 'roca', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (249, 'carla', 'casas', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (250, 'joan', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (251, 'adria', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (252, 'joan', 'sanz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (253, 'marc', 'molina', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (254, 'eric', 'serra', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (255, 'oriol', 'molina', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (256, 'adria', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (257, 'oriol', 'ortega', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (258, 'pau', 'ferrer', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (259, 'nora', 'font', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (260, 'carla', 'garcia', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (261, 'nil', 'iglesias', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (262, 'pau', 'navarro', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (263, 'pau', 'garcia', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (264, 'carla', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (265, 'laia', 'campos', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (266, 'eric', 'marti', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (267, 'pol', 'pujol', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (268, 'irene', 'navarro', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (269, 'adria', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (270, 'irene', 'ortega', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (271, 'marc', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (272, 'david', 'roca', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (273, 'carla', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (274, 'adria', 'casas', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (275, 'adria', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (276, 'david', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (277, 'marc', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (278, 'nil', 'font', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (279, 'xavi', 'font', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (280, 'clara', 'rovira', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (281, 'anna', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (282, 'marc', 'garcia', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (283, 'oriol', 'vidal', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (284, 'eric', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (285, 'jordi', 'ruiz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (286, 'irene', 'sanz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (287, 'xavi', 'ruiz', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (288, 'clara', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (289, 'laia', 'garcia', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (290, 'nora', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (291, 'berta', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (292, 'pau', 'pujol', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (293, 'clara', 'molina', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (294, 'joan', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (295, 'irene', 'sanz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (296, 'oriol', 'duran', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (297, 'laia', 'navarro', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (298, 'marc', 'soler', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (299, 'laia', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (300, 'oriol', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (301, 'anna', 'font', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (302, 'irene', 'casas', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (303, 'eric', 'campos', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (304, 'irene', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (305, 'pau', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (306, 'pol', 'molina', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (307, 'nil', 'garcia', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (308, 'jordi', 'rovira', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (309, 'carla', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (310, 'pol', 'pujol', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (311, 'adria', 'garcia', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (312, 'nora', 'rovira', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (313, 'carla', 'ferrer', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (314, 'jordi', 'sanz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (315, 'berta', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (316, 'aina', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (317, 'marc', 'roca', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (318, 'david', 'soler', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (319, 'oriol', 'sanz', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (320, 'marta', 'ferrer', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (321, 'eric', 'costa', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (322, 'berta', 'sanz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (323, 'anna', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (324, 'eric', 'rovira', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (325, 'xavi', 'font', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (326, 'nora', 'serra', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (327, 'adria', 'pujol', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (328, 'laia', 'ferrer', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (329, 'pol', 'costa', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (330, 'pol', 'marti', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (331, 'xavi', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (332, 'carla', 'duran', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (333, 'joan', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (334, 'david', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (335, 'pau', 'casas', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (336, 'pol', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (337, 'laia', 'marti', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (338, 'nora', 'marti', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (339, 'pol', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (340, 'joan', 'ortega', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (341, 'irene', 'molina', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (342, 'eric', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (343, 'david', 'pujol', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (344, 'irene', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (345, 'oriol', 'marti', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (346, 'aina', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (347, 'eric', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (348, 'nora', 'serra', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (349, 'clara', 'ortega', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (350, 'xavi', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (351, 'joan', 'navarro', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (352, 'nil', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (353, 'jordi', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (354, 'marta', 'ruiz', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (355, 'aina', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (356, 'anna', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (357, 'joan', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (358, 'irene', 'pujol', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (359, 'pol', 'vidal', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (360, 'laia', 'pujol', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (361, 'irene', 'serra', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (362, 'anna', 'rovira', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (363, 'clara', 'molina', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (364, 'david', 'roca', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (365, 'aina', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (366, 'xavi', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (367, 'berta', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (368, 'xavi', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (369, 'eric', 'ruiz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (370, 'laia', 'duran', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (371, 'xavi', 'sanz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (372, 'joan', 'ferrer', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (373, 'david', 'casas', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (374, 'nora', 'campos', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (375, 'anna', 'font', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (376, 'pau', 'font', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (377, 'nil', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (378, 'clara', 'duran', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (379, 'clara', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (380, 'oriol', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (381, 'marta', 'navarro', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (382, 'joan', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (383, 'marc', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (384, 'pau', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (385, 'berta', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (386, 'jordi', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (387, 'adria', 'ortega', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (388, 'xavi', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (389, 'aina', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (390, 'marc', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (391, 'eric', 'rovira', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (392, 'anna', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (393, 'berta', 'campos', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (394, 'jordi', 'roca', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (395, 'david', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (396, 'david', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (397, 'marta', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (398, 'oriol', 'font', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (399, 'oriol', 'pujol', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (400, 'pau', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (401, 'carla', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (402, 'anna', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (403, 'jordi', 'pujol', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (404, 'xavi', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (405, 'clara', 'pujol', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (406, 'xavi', 'sanz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (407, 'eric', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (408, 'xavi', 'sanz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (409, 'irene', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (410, 'nora', 'rovira', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (411, 'clara', 'casas', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (412, 'pau', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (413, 'oriol', 'vidal', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (414, 'adria', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (415, 'berta', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (416, 'nora', 'roca', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (417, 'nil', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (418, 'laia', 'roca', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (419, 'xavi', 'navarro', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (420, 'joan', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (421, 'marc', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (422, 'david', 'marti', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (423, 'carla', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (424, 'oriol', 'casas', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (425, 'pol', 'ortega', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (426, 'clara', 'casas', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (427, 'aina', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (428, 'carla', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (429, 'jordi', 'costa', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (430, 'marc', 'sanz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (431, 'oriol', 'roca', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (432, 'anna', 'font', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (433, 'marc', 'garcia', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (434, 'joan', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (435, 'clara', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (436, 'clara', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (437, 'berta', 'costa', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (438, 'eric', 'ortega', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (439, 'nora', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (440, 'marta', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (441, 'jordi', 'marti', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (442, 'laia', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (443, 'aina', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (444, 'anna', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (445, 'oriol', 'molina', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (446, 'xavi', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (447, 'adria', 'soler', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (448, 'berta', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (449, 'irene', 'marti', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (450, 'carla', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (451, 'carla', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (452, 'marc', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (453, 'nil', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (454, 'adria', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (455, 'pau', 'sanz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (456, 'marta', 'ortega', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (457, 'marta', 'font', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (458, 'nora', 'garcia', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (459, 'xavi', 'ortega', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (460, 'berta', 'costa', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (461, 'pol', 'vidal', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (462, 'jordi', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (463, 'joan', 'duran', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (464, 'oriol', 'campos', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (465, 'berta', 'campos', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (466, 'joan', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (467, 'joan', 'roca', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (468, 'clara', 'ruiz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (469, 'marc', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (470, 'adria', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (471, 'pol', 'campos', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (472, 'carla', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (473, 'irene', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (474, 'nora', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (475, 'jordi', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (476, 'laia', 'serra', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (477, 'pau', 'molina', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (478, 'oriol', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (479, 'eric', 'costa', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (480, 'aina', 'pujol', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (481, 'anna', 'sanz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (482, 'jordi', 'serra', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (483, 'pau', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (484, 'xavi', 'casas', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (485, 'oriol', 'pujol', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (486, 'aina', 'pujol', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (487, 'carla', 'duran', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (488, 'david', 'vidal', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (489, 'eric', 'serra', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (490, 'xavi', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (491, 'adria', 'ortega', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (492, 'pau', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (493, 'nil', 'casas', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (494, 'joan', 'vidal', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (495, 'laia', 'casas', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (496, 'nora', 'roca', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (497, 'eric', 'vidal', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (498, 'adria', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (499, 'david', 'casas', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (500, 'carla', 'campos', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (501, 'oriol', 'marti', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (502, 'marc', 'marti', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (503, 'joan', 'garcia', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (504, 'aina', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (505, 'marta', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (506, 'david', 'pujol', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (507, 'oriol', 'ruiz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (508, 'eric', 'duran', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (509, 'aina', 'ortega', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (510, 'marta', 'rovira', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (511, 'marta', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (512, 'aina', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (513, 'david', 'rovira', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (514, 'pol', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (515, 'nora', 'navarro', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (516, 'eric', 'campos', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (517, 'pau', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (518, 'xavi', 'soler', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (519, 'berta', 'marti', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (520, 'carla', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (521, 'marta', 'roca', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (522, 'nora', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (523, 'irene', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (524, 'nil', 'duran', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (525, 'laia', 'iglesias', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (526, 'clara', 'ruiz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (527, 'jordi', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (528, 'marta', 'font', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (529, 'nil', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (530, 'marta', 'vidal', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (531, 'marta', 'soler', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (532, 'laia', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (533, 'jordi', 'iglesias', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (534, 'marc', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (535, 'eric', 'iglesias', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (536, 'berta', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (537, 'marc', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (538, 'pol', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (539, 'laia', 'duran', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (540, 'carla', 'duran', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (541, 'xavi', 'sanz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (542, 'nil', 'navarro', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (543, 'pau', 'ferrer', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (544, 'nora', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (545, 'marta', 'duran', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (546, 'eric', 'rovira', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (547, 'anna', 'iglesias', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (548, 'aina', 'ferrer', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (549, 'irene', 'vidal', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (550, 'irene', 'ortega', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (551, 'anna', 'marti', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (552, 'laia', 'pujol', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (553, 'berta', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (554, 'carla', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (555, 'laia', 'garcia', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (556, 'adria', 'casas', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (557, 'nil', 'campos', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (558, 'aina', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (559, 'carla', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (560, 'marc', 'ferrer', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (561, 'irene', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (562, 'irene', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (563, 'anna', 'serra', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (564, 'aina', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (565, 'nil', 'casas', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (566, 'adria', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (567, 'laia', 'font', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (568, 'marta', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (569, 'nora', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (570, 'irene', 'casas', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (571, 'david', 'campos', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (572, 'oriol', 'costa', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (573, 'berta', 'costa', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (574, 'xavi', 'soler', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (575, 'xavi', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (576, 'pau', 'duran', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (577, 'aina', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (578, 'joan', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (579, 'carla', 'sanz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (580, 'jordi', 'pujol', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (581, 'clara', 'ortega', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (582, 'aina', 'iglesias', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (583, 'clara', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (584, 'nil', 'molina', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (585, 'carla', 'ruiz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (586, 'clara', 'pujol', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (587, 'berta', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (588, 'jordi', 'vidal', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (589, 'pau', 'font', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (590, 'berta', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (591, 'anna', 'vidal', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (592, 'pau', 'sanz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (593, 'clara', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (594, 'nora', 'ferrer', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (595, 'carla', 'casas', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (596, 'adria', 'duran', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (597, 'berta', 'serra', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (598, 'anna', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (599, 'jordi', 'vidal', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (600, 'xavi', 'roca', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (601, 'adria', 'font', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (602, 'marta', 'roca', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (603, 'xavi', 'serra', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (604, 'xavi', 'soler', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (605, 'nil', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (606, 'berta', 'iglesias', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (607, 'pol', 'pujol', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (608, 'oriol', 'ferrer', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (609, 'adria', 'navarro', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (610, 'aina', 'marti', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (611, 'carla', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (612, 'oriol', 'navarro', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (613, 'nil', 'sanz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (614, 'adria', 'iglesias', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (615, 'eric', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (616, 'pol', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (617, 'pau', 'casas', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (618, 'pol', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (619, 'irene', 'costa', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (620, 'adria', 'duran', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (621, 'clara', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (622, 'nil', 'garcia', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (623, 'anna', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (624, 'oriol', 'roca', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (625, 'nil', 'garcia', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (626, 'nil', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (627, 'pol', 'casas', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (628, 'david', 'pujol', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (629, 'nora', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (630, 'irene', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (631, 'aina', 'molina', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (632, 'jordi', 'sanz', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (633, 'pau', 'ortega', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (634, 'joan', 'campos', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (635, 'irene', 'campos', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (636, 'oriol', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (637, 'jordi', 'duran', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (638, 'irene', 'sanz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (639, 'berta', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (640, 'marta', 'molina', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (641, 'clara', 'ortega', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (642, 'anna', 'ferrer', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (643, 'laia', 'font', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (644, 'pau', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (645, 'jordi', 'iglesias', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (646, 'aina', 'soler', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (647, 'berta', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (648, 'jordi', 'iglesias', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (649, 'clara', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (650, 'aina', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (651, 'nora', 'garcia', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (652, 'xavi', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (653, 'pol', 'roca', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (654, 'eric', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (655, 'marc', 'duran', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (656, 'aina', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (657, 'berta', 'sanz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (658, 'xavi', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (659, 'david', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (660, 'jordi', 'campos', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (661, 'eric', 'duran', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (662, 'marc', 'molina', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (663, 'nora', 'costa', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (664, 'laia', 'duran', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (665, 'nil', 'molina', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (666, 'david', 'duran', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (667, 'pol', 'serra', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (668, 'adria', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (669, 'clara', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (670, 'xavi', 'serra', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (671, 'irene', 'costa', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (672, 'laia', 'soler', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (673, 'irene', 'font', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (674, 'eric', 'campos', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (675, 'marta', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (676, 'jordi', 'soler', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (677, 'eric', 'pujol', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (678, 'irene', 'ruiz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (679, 'jordi', 'ferrer', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (680, 'carla', 'iglesias', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (681, 'pau', 'duran', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (682, 'david', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (683, 'david', 'molina', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (684, 'irene', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (685, 'nora', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (686, 'anna', 'duran', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (687, 'oriol', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (688, 'pol', 'roca', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (689, 'irene', 'iglesias', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (690, 'jordi', 'roca', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (691, 'laia', 'ortega', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (692, 'aina', 'pujol', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (693, 'marc', 'pujol', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (694, 'pol', 'garcia', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (695, 'adria', 'sanz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (696, 'pol', 'marti', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (697, 'pol', 'marti', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (698, 'marta', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (699, 'irene', 'marti', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (700, 'adria', 'roca', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (701, 'marc', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (702, 'anna', 'molina', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (703, 'clara', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (704, 'laia', 'ortega', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (705, 'pol', 'molina', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (706, 'marta', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (707, 'carla', 'vidal', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (708, 'nil', 'font', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (709, 'carla', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (710, 'clara', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (711, 'nora', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (712, 'laia', 'font', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (713, 'david', 'molina', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (714, 'marc', 'soler', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (715, 'nora', 'sanz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (716, 'nil', 'marti', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (717, 'eric', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (718, 'pau', 'serra', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (719, 'aina', 'rovira', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (720, 'berta', 'duran', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (721, 'nora', 'ferrer', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (722, 'adria', 'serra', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (723, 'marc', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (724, 'nil', 'garcia', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (725, 'pol', 'roca', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (726, 'carla', 'pujol', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (727, 'aina', 'sanz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (728, 'oriol', 'marti', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (729, 'aina', 'ortega', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (730, 'eric', 'serra', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (731, 'laia', 'serra', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (732, 'nil', 'ruiz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (733, 'marta', 'campos', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (734, 'nora', 'iglesias', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (735, 'carla', 'garcia', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (736, 'jordi', 'molina', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (737, 'david', 'rovira', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (738, 'xavi', 'ortega', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (739, 'laia', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (740, 'berta', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (741, 'nil', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (742, 'xavi', 'molina', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (743, 'laia', 'roca', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (744, 'irene', 'ortega', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (745, 'marta', 'ferrer', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (746, 'marc', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (747, 'nil', 'pujol', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (748, 'irene', 'ferrer', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (749, 'pol', 'iglesias', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (750, 'joan', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (751, 'marta', 'garcia', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (752, 'pol', 'navarro', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (753, 'berta', 'navarro', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (754, 'jordi', 'campos', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (755, 'aina', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (756, 'laia', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (757, 'jordi', 'vidal', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (758, 'xavi', 'rovira', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (759, 'adria', 'marti', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (760, 'marc', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (761, 'marta', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (762, 'nil', 'duran', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (763, 'david', 'navarro', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (764, 'marta', 'serra', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (765, 'carla', 'rovira', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (766, 'jordi', 'pujol', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (767, 'berta', 'casas', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (768, 'eric', 'sanz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (769, 'laia', 'ruiz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (770, 'carla', 'vidal', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (771, 'xavi', 'serra', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (772, 'eric', 'font', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (773, 'joan', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (774, 'eric', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (775, 'clara', 'casas', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (776, 'oriol', 'font', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (777, 'clara', 'casas', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (778, 'irene', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (779, 'jordi', 'costa', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (780, 'nora', 'pujol', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (781, 'nil', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (782, 'david', 'serra', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (783, 'pau', 'rovira', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (784, 'berta', 'vidal', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (785, 'berta', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (786, 'jordi', 'rovira', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (787, 'adria', 'navarro', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (788, 'anna', 'vidal', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (789, 'berta', 'ferrer', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (790, 'eric', 'font', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (791, 'david', 'navarro', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (792, 'eric', 'vidal', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (793, 'nil', 'molina', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (794, 'jordi', 'vidal', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (795, 'marta', 'vidal', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (796, 'clara', 'vidal', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (797, 'marta', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (798, 'xavi', 'iglesias', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (799, 'irene', 'campos', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (800, 'berta', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (801, 'david', 'molina', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (802, 'laia', 'ferrer', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (803, 'anna', 'campos', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (804, 'joan', 'costa', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (805, 'marta', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (806, 'marta', 'font', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (807, 'oriol', 'duran', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (808, 'nora', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (809, 'eric', 'navarro', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (810, 'berta', 'ferrer', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (811, 'berta', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (812, 'nora', 'duran', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (813, 'jordi', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (814, 'pol', 'ferrer', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (815, 'pol', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (816, 'marta', 'rovira', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (817, 'oriol', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (818, 'berta', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (819, 'david', 'ferrer', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (820, 'xavi', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (821, 'irene', 'pujol', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (822, 'eric', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (823, 'irene', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (824, 'aina', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (825, 'clara', 'navarro', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (826, 'anna', 'ortega', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (827, 'jordi', 'font', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (828, 'berta', 'serra', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (829, 'aina', 'font', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (830, 'nora', 'marti', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (831, 'pau', 'marti', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (832, 'marc', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (833, 'marc', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (834, 'carla', 'marti', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (835, 'eric', 'duran', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (836, 'joan', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (837, 'aina', 'pujol', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (838, 'xavi', 'marti', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (839, 'jordi', 'iglesias', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (840, 'nil', 'iglesias', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (841, 'oriol', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (842, 'clara', 'molina', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (843, 'pau', 'marti', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (844, 'anna', 'garcia', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (845, 'clara', 'ruiz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (846, 'jordi', 'roca', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (847, 'eric', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (848, 'clara', 'garcia', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (849, 'laia', 'rovira', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (850, 'irene', 'roca', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (851, 'laia', 'font', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (852, 'pol', 'sanz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (853, 'berta', 'campos', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (854, 'anna', 'campos', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (855, 'aina', 'marti', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (856, 'joan', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (857, 'aina', 'molina', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (858, 'anna', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (859, 'aina', 'ortega', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (860, 'aina', 'font', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (861, 'nil', 'ruiz', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (862, 'anna', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (863, 'carla', 'molina', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (864, 'joan', 'costa', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (865, 'irene', 'serra', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (866, 'carla', 'navarro', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (867, 'pol', 'ruiz', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (868, 'nil', 'molina', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (869, 'clara', 'molina', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (870, 'eric', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (871, 'xavi', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (872, 'joan', 'casas', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (873, 'aina', 'pujol', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (874, 'carla', 'costa', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (875, 'eric', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (876, 'adria', 'molina', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (877, 'pol', 'roca', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (878, 'aina', 'vidal', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (879, 'pol', 'marti', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (880, 'adria', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (881, 'anna', 'pujol', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (882, 'nil', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (883, 'pol', 'roca', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (884, 'aina', 'rovira', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (885, 'marc', 'iglesias', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (886, 'nil', 'campos', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (887, 'jordi', 'font', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (888, 'eric', 'duran', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (889, 'eric', 'garcia', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (890, 'irene', 'navarro', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (891, 'irene', 'roca', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (892, 'eric', 'pujol', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (893, 'joan', 'ferrer', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (894, 'nora', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (895, 'joan', 'molina', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (896, 'adria', 'iglesias', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (897, 'adria', 'casas', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (898, 'laia', 'roca', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (899, 'laia', 'molina', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (900, 'pau', 'rovira', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (901, 'marta', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (902, 'oriol', 'marti', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (903, 'marta', 'garcia', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (904, 'jordi', 'duran', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (905, 'carla', 'ruiz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (906, 'pau', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (907, 'marc', 'serra', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (908, 'oriol', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (909, 'adria', 'vidal', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (910, 'aina', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (911, 'irene', 'soler', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (912, 'nil', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (913, 'joan', 'navarro', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (914, 'jordi', 'soler', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (915, 'xavi', 'marti', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (916, 'jordi', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (917, 'pau', 'ortega', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (918, 'pau', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (919, 'nil', 'ortega', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (920, 'xavi', 'ortega', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (921, 'pau', 'ruiz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (922, 'berta', 'iglesias', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (923, 'berta', 'font', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (924, 'adria', 'costa', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (925, 'oriol', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (926, 'clara', 'pujol', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (927, 'marc', 'rovira', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (928, 'irene', 'marti', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (929, 'nora', 'ruiz', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (930, 'aina', 'soler', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (931, 'marta', 'duran', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (932, 'xavi', 'costa', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (933, 'anna', 'soler', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (934, 'david', 'roca', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (935, 'aina', 'ortega', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (936, 'carla', 'garcia', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (937, 'adria', 'ferrer', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (938, 'david', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (939, 'pol', 'iglesias', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (940, 'nil', 'vidal', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (941, 'nil', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (942, 'pau', 'duran', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (943, 'marc', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (944, 'pau', 'ortega', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (945, 'marta', 'serra', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (946, 'irene', 'duran', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (947, 'berta', 'campos', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (948, 'nora', 'ortega', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (949, 'berta', 'ruiz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (950, 'xavi', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (951, 'xavi', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (952, 'berta', 'vidal', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (953, 'xavi', 'soler', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (954, 'adria', 'ruiz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (955, 'aina', 'ruiz', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (956, 'jordi', 'ferrer', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (957, 'berta', 'vidal', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (958, 'xavi', 'rovira', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (959, 'nora', 'navarro', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (960, 'marta', 'font', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (961, 'marc', 'font', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (962, 'aina', 'costa', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (963, 'pol', 'sanz', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (964, 'pau', 'navarro', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (965, 'marta', 'ortega', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (966, 'carla', 'campos', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (967, 'david', 'casas', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (968, 'carla', 'molina', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (969, 'aina', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (970, 'aina', 'sanz', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (971, 'pau', 'costa', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (972, 'laia', 'roca', 'quantumapps');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (973, 'marc', 'vidal', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (974, 'adria', 'ferrer', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (975, 'pol', 'rovira', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (976, 'carla', 'molina', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (977, 'joan', 'soler', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (978, 'anna', 'rovira', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (979, 'berta', 'serra', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (980, 'nora', 'pujol', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (981, 'berta', 'navarro', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (982, 'pol', 'font', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (983, 'marc', 'serra', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (984, 'oriol', 'marti', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (985, 'oriol', 'ortega', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (986, 'pol', 'vidal', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (987, 'adria', 'sanz', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (988, 'nora', 'garcia', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (989, 'xavi', 'soler', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (990, 'marta', 'ortega', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (991, 'jordi', 'sanz', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (992, 'marc', 'font', 'tech corp');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (993, 'pol', 'rovira', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (994, 'nora', 'duran', 'data solutions');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (995, 'marta', 'vidal', 'cyberlayer');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (996, 'marta', 'sanz', 'nextgen systems');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (997, 'laia', 'ortega', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (998, 'clara', 'ortega', 'cloudnova');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (999, 'aina', 'ferrer', 'bluebyte');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (1000, 'pau', 'costa', 'netsecure');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (1001, 'nil', 'font', 'futuresoft');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (1002, 'marta', 'pujol', 'innovate asix');
INSERT INTO dades_ponent (id, nom, cognom, empresa) VALUES (1003, 'xavi', 'pujol', 'netsecure');